import { profileRequestData } from "../../../misc/interfaces";
import sleep from "../../../misc/sleep";
import RequestManager from "../../classes/RequestManager";
import RpProfile from "../../classes/RpProfile";

export default
async function processBackLog(this:RequestManager){
    
    this.profileProcessing = true;
    console.log("Processing backlog of " + this.profileRequests.length + " requests");

    for (let i = 0; i < this.profileRequests.length; i++) {
        const request = this.profileRequests[i] as unknown as profileRequestData;
        const startTime = Date.now();
        console.log("Processing backlog request " + i + " of " + this.profileRequests.length);
        const profileName = await RpProfile.assignNewProfile(request, this);

        if(profileName){
           this.a3DebugMsg("Profile " + profileName + " generated by GPT-3 in " + (Date.now() - startTime) + "ms");

           if(this.profileRequests.length-i > 0){
                 this.a3DebugMsg("Backlog of " + (this.profileRequests.length-i) + " requests remaining");
            };

        };

        // await sleep(3000); // Wait 3 second before sending next request, to avoid 429 errors.
        
        this.profileRequests.splice(i, 1);
        i--; 
        
      }

    this.profileProcessing = false;

};